### ISSUE TITLE
Enable strategies during setup

### ISSUE THREAD

**Issue by auryn-macmillan** [TokenWalk/galleryDAO#5]
It would be nice to be able to enable strategies during deployment/on `setup()`.

**Comment by nginnever** [comment]
ah so strategies need to be made aware of the proposal module deployment, making the proposal module constructor unable to set them up. Create2 would need to know the init params of the seele module which contains the strategy address that would need the seele module address.

Let me know if you have any suggestions on how to make this work

**Comment by nginnever** [comment]
I suppose an alternative could be registering the proposal module in a subsequent transaction to the strategies

**Comment by auryn-macmillan** [comment]
Yeah, that's kind of what I was thinking.
If we can deploy both to a deterministic address, then we can batch all of the calls to deploy and initialize.
