### ISSUE TITLE
onlyAvatar() should be onlyOwner()

### ISSUE THREAD

**Issue by auryn-macmillan** [TokenWalk/galleryDAO#6]
`onlyAvatar()` should probably be `onlyOwner()` in most cases.

- [ ] It's unused in `Seele.sol`, so should probably be removed.
  - [ ] https://github.com/TokenWalk/Seele/blob/8f1a34e1990e6b4ff541e519d4979ade971b8b5e/contracts/Seele.sol#L51
- [ ] in `Seele.sol` `avatar` should be replaced with `owner` in some places
  - [ ] https://github.com/TokenWalk/Seele/blob/8f1a34e1990e6b4ff541e519d4979ade971b8b5e/contracts/Seele.sol#L237
- [ ] In `Strategy.sol` it should be switched to should be replaced with `onlyOwner()`
  - [ ] https://github.com/TokenWalk/Seele/blob/8f1a34e1990e6b4ff541e519d4979ade971b8b5e/contracts/votingStrategies/Strategy.sol#L11
  - [ ] https://github.com/TokenWalk/Seele/blob/8f1a34e1990e6b4ff541e519d4979ade971b8b5e/contracts/votingStrategies/Strategy.sol#L23
  - [ ] https://github.com/TokenWalk/Seele/blob/8f1a34e1990e6b4ff541e519d4979ade971b8b5e/contracts/votingStrategies/Strategy.sol#L29

Looks like it's also being used in `CompoundBravoVoting.sol`, `MemberLinearVoting.sol`, `MemberQuadraticVoting.sol`, `NFTSingleVoting.sol`, `OZLinearVoting.sol`, `RealityERC20Voting.sol`, `SingleVoting.sol`, and `StakedVoting.sol`.

Presumably, `owner()` should be the same as the Seele module, so it could perhaps read from that contract's state, rather than storing its own state.

**Comment by nginnever** [comment]
Switches `avatar` to `owner`

https://github.com/TokenWalk/Seele/commit/8a86c528cad0846f408c131a94cc8437e9daaaf7
