### ISSUE TITLE
Zero address checks probably not necessary

### ISSUE THREAD

**Issue by auryn-macmillan** [TokenWalk/galleryDAO#7]
It's probably not necessary to require that these are not zero addresses, since `owner` can presumably change them after the fact if they do it accidentally.
https://github.com/TokenWalk/Seele/blob/8f1a34e1990e6b4ff541e519d4979ade971b8b5e/contracts/Seele.sol#L86-L87

Although we should perhaps check for that for `owner`.
https://github.com/TokenWalk/Seele/blob/8f1a34e1990e6b4ff541e519d4979ade971b8b5e/contracts/Seele.sol#L91

**Comment by nginnever** [comment]
Ahh right, I picked that pattern up from the bridge module but forgot that `setAvatar` and `setTarget` are owner bound.
```
Although we should perhaps check for that for owner.
```
`transferOwnership` has a 0 address check in it.

**Comment by auryn-macmillan** [comment]
> transferOwnership has a 0 address check in it.

Ah yes, of course.
