### ISSUE TITLE
Should _proposal.proposer be able to cancel their proposal?

### ISSUE THREAD

**Issue by auryn-macmillan** [TokenWalk/galleryDAO#8]
I see the rationale for the proposer to be able to cancel their proposal (maybe they made an typo or an error in the included transactions, etc), but this also potentially opens a route to the proposer having some privileged access to manipulating proposals.

I wonder if there is a more sensible compromise here? Two options that come to mind:
1. proposer cannot delete once anyone else has cast a vote
2. proposer cannot delete after some amount of time has passed

I'm sure there are other reasonable conditions one might put on this, so I wonder if it should actually be deferred to the strategy? So calling `cancelProposal()` would then check with the strategy to determine if the proposal can actually be cancelled.

**Comment by nginnever** [comment]
This is a good point and a nice abstraction as well. Letting the strategies implement their own cancel logic seems like the way to go.

**Comment by nginnever** [comment]
One issue with consulting the strategy here is that it won't work if the strategy is on a sidechain via a bridge. I think I would be more inclined to only let proposals be cancelable by `owner` in this case and just reuse the cancel function for [issue 9](https://github.com/TokenWalk/Seele/issues/9) with a special role for an account or committee to only cancel malicious or mistaken proposals.

Votes can still happen on the strategy but I assume a social solution or an external protocol to check if a proposal is still not canceled before voting.

 This gives more power to the role that can cancel proposal to grief voters before canceling but this is a more trusted role.

**Comment by nginnever** [comment]
Only the owner can cancel https://github.com/TokenWalk/Seele/commit/c6c749b7018be64d43e4c443287d0ad57559e037

**Comment by auryn-macmillan** [comment]
> One issue with consulting the strategy here is that it won't work if the strategy is on a sidechain via a bridge

A strategy in a different network would still need a local proxy. So the cancel logic would just live there, no?

Nevertheless, I think it's worth considering the likely layout of an organization that exists across chains/layers. My guess is that in the vast majority of cases, Seele and it's strategies would love on the same network, because there would be little benefit if running them on separate networks.

The more likely setup is.

```
Safe < bridge module < L2/sidechain bridge < Seele < Strategy
```

**Comment by nginnever** [comment]
The benefit of keeping Seele and the strategy on different networks that I can see would be for multiple transaction proposals, only bridging one `receiveStrategy` transaction as apposed to many `execTransactionFromModule` transactions.

```
Safe < Seele < bridge strategy <  L2/sidechain bridge < Voting Strategy
```

But for this to work there also needs to be one transaction the other direction to init voting
```
Seele > bridge strategy > L2/sidechain bridge > Voting Strategy
```

Either setup will work, but I think generally it's a good idea to limit the calls between `Seele <-> strategy`. 

Strategies can still implement their own cancel logic and stop a proposal within the strategy as well.

**Comment by auryn-macmillan** [comment]
> only bridging one receiveStrategy transaction as apposed to many execTransactionFromModule transactions.
That's fair.

> Strategies can still implement their own cancel logic and stop a proposal within the strategy as well.
That's also a good point. Which makes me wonder if the cancel logic in the Seele contract should just be removed altogether?

**Comment by nginnever** [comment]
>That's also a good point. Which makes me wonder if the cancel logic in the Seele contract should just be removed altogether?

I think it's still valuable to keep the cancel logic on the Seele contract since the delay logic is there as well. This gives cancel guards/committees the ability to stop proposals in the delay period, not just the voting period.
