### ISSUE TITLE
How to stop griefing / malicious proposals?

### ISSUE THREAD

**Issue by auryn-macmillan** [TokenWalk/galleryDAO#9]
Let's say I have two strategies enabled:
1. slow moving strategy for community proposals
2. fast strategy controlled by trusted community members as safe guard against malicious proposals

How does 2 guard against griefing and/or malicious proposals by 1?
So far as I can tell, the only way they could do it currently would be to disable 1.
Perhaps it would be good to have an `onlyOwner()` function `markProposalsInvalid(uint256[] proposals)` to mark proposals as invalid?

**Comment by nginnever** [comment]
Agreed, currently using the `cancelProposal` function for this, where `onlyOwner` can cancel. This will allow a strategy like a  `proposalGuard` to be scoped only to being able to cancel certain proposals in a timely manor.

**Comment by nginnever** [comment]
Prototype of a proposal guard strategy can be found [here](https://github.com/TokenWalk/Seele/blob/master/contracts/utilityStrategies/ProposalGuard.sol)

**Comment by auryn-macmillan** [comment]
I wonder if there should be a `cancelProposals()` function as well, so that you can cancel multiple proposals in one call? Just to reduce the griefing factor?

**Comment by nginnever** [comment]
can now cancel multiple proposals https://github.com/HyphalDAO/Seele/commit/5ff48b2b8c722fefaa6ba5056f6b9cccfc11b3bd
